### ISSUE TITLE
Add meta tags / Favicon / PWA

### ISSUE THREAD

**Issue by josch87** [josch87/Gunther#30]
## Value proposition

As a user
I want to see an app logo and name in prominent places
So that I can identify the app on first sight

## Acceptance criteria

- [x] A favicon is displayed on all important clients (Chrome, Firefox, Edge, Safari etc.)
- [x] Descriptive meta title is displayed on all pages such as "Gunther – Contacts" for the Contacts Page
- [x] When the client supports it, the client offers to install the app on the device (as a progressive web app)

**Comment by Roland-Hufnagel** [comment]
I recommend to put a wireframe to the description that gives an idea of app logo and name. 
Are you sure, you want the third Acceptance criteria???
And as Ruben said, it's helpful for others to give your US a number.
